#pragma once
#include <string>
#include <map>
#include <memory>
#include <unordered_map>
#include <vector>
#include <deque>
#include <functional>
#include <iostream>
#include <array>
#include "SpectralAssert.h"
#include "Logger.h"
#include "filesystem"
